# Generated by Django 3.2.3 on 2021-06-08 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('display_name', models.CharField(max_length=200)),
                ('gender', models.BooleanField(null=True)),
                ('status', models.TextField(default='', null=True)),
            ],
            options={
                'db_table': 'faceval_user',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotoBlog',
            fields=[
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('path', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('trained', models.BooleanField(default=False)),
                ('score', models.FloatField(null=True)),
                ('face_positions', models.TextField()),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_provider.profile')),
            ],
            options={
                'db_table': 'photo',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('date_added', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('path', models.TextField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_provider.profile')),
            ],
            options={
                'db_table': 'model',
                'abstract': False,
            },
        ),
    ]
