# Generated by Django 3.2.3 on 2021-06-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoblog',
            name='image',
            field=models.TextField(),
        ),
    ]
